/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:017785db-e448-4caa-8ff5-5912a4758ba4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_T1kvcsmTk",
    "aws_user_pools_web_client_id": "4skqlqv5ebpjrgu7pvnc3gp38c",
    "oauth": {}
};


export default awsmobile;
