/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:40c41416-10a4-44e4-a48d-3d5d493bdc97",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_a1PgoxdjY",
    "aws_user_pools_web_client_id": "305sbenpeoffoip7adn1m4lm7r",
    "oauth": {}
};


export default awsmobile;
