/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e2ea0147-cc32-465f-b0e0-e4129aa64f3e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kj6L9zlVe",
    "aws_user_pools_web_client_id": "76smlcohhncn970qa74njnclto",
    "oauth": {}
};


export default awsmobile;
